import React,{useEffect,useId,useRef,useState} from 'react'
import {componentSpecs} from './system'
import {Icon,iconNames,IconName} from './Icon'
import {Button,DestructiveButton,IconButton,InputField,Textarea,SelectField,SelectOption,Checkbox,Radio,RadioGroup,Switch,Badge,Avatar,TabItem,Alert,DoctorCard,AppointmentCard,DeviceCheckRow,FaceGuidanceStatus,CameraGuidanceOverlay,CallControl,DesktopHeader} from './VelloraComponents'
import {ComponentPage} from './ComponentPage'

const TextCtl=({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void})=><label>{label}<input type="text" value={value} onChange={e=>onChange(e.target.value)}/></label>
const SelectCtl=({label,value,options,onChange}:{label:string;value:string;options:readonly string[];onChange:(v:any)=>void})=><label>{label}<select value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></label>
const CheckCtl=({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void})=><label className="control-check"><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/>{label}</label>
const States=({children}:{children:React.ReactNode})=><div className="state-lab">{children}</div>
const StateItem=({label,children}:{label:string;children:React.ReactNode})=><div className="state-item">{children}<small>{label}</small></div>

function ButtonPage(){const spec=componentSpecs.button;const[style,setStyle]=useState<'Primary'|'Secondary'|'Ghost'>('Primary');const[size,setSize]=useState<'Medium'|'Large'>('Medium');const[label,setLabel]=useState('Continuar');const[showIcon,setShowIcon]=useState(false);const[disabled,setDisabled]=useState(false);const[log,setLog]=useState('');
 const controls=<><SelectCtl label="style" value={style} options={['Primary','Secondary','Ghost']} onChange={setStyle}/><SelectCtl label="size" value={size} options={['Medium','Large']} onChange={setSize}/><TextCtl label="label" value={label} onChange={setLabel}/><CheckCtl label="showIcon" value={showIcon} onChange={setShowIcon}/><CheckCtl label="disabled" value={disabled} onChange={setDisabled}/></>
 const states=<States>{(['Default','Hover','Focused','Pressed','Disabled'] as const).map(s=><StateItem key={s} label={s}><Button label="Continuar" state={s}/></StateItem>)}</States>
 const code=`import { Button } from './VelloraComponents'\n\n<Button\n  label="${label}"\n  style="${style}"\n  size="${size}"\n  showIcon={${showIcon}}\n  disabled={${disabled}}\n  onClick={() => {}}\n/>`
 return <ComponentPage spec={spec} preview={<Button label={label} style={style} size={size} showIcon={showIcon} icon={<Icon name="Arrow Left" size={20}/>} disabled={disabled} onClick={()=>setLog('onClick executado')}/>} controls={controls} code={code} stateLab={states} eventLog={log}/>}
function DestructivePage(){const spec=componentSpecs['button-destructive'];const[size,setSize]=useState<'Medium'|'Large'>('Medium');const[label,setLabel]=useState('Cancelar consulta');const[showIcon,setShowIcon]=useState(false);const[disabled,setDisabled]=useState(false);const[log,setLog]=useState('');
 return <ComponentPage spec={spec} preview={<DestructiveButton label={label} size={size} showIcon={showIcon} icon={<Icon name="Warning" size={20}/>} disabled={disabled} onClick={()=>setLog('Ação disparada. Confirmação pertence ao fluxo consumidor.')}/>} controls={<><SelectCtl label="size" value={size} options={['Medium','Large']} onChange={setSize}/><TextCtl label="label" value={label} onChange={setLabel}/><CheckCtl label="showIcon" value={showIcon} onChange={setShowIcon}/><CheckCtl label="disabled" value={disabled} onChange={setDisabled}/></>} code={`<DestructiveButton label="${label}" size="${size}" showIcon={${showIcon}} disabled={${disabled}} onClick={() => {}} />`} stateLab={<States>{(['Default','Hover','Focused','Pressed','Disabled'] as const).map(s=><StateItem key={s} label={s}><DestructiveButton state={s}/></StateItem>)}</States>} eventLog={log}/>}
function IconButtonPage(){const spec=componentSpecs['icon-button'];const[size,setSize]=useState<'Medium'|'Large'>('Medium');const[style,setStyle]=useState<'Primary'|'Secondary'|'Ghost'>('Ghost');const[icon,setIcon]=useState<IconName>('Bell');const[label,setLabel]=useState('Notificações');const[pressed,setPressed]=useState(false);const[disabled,setDisabled]=useState(false);const[log,setLog]=useState('');
 const renderedIcon=<Icon name={icon} size={20}/>
 return <ComponentPage spec={spec} preview={<IconButton icon={renderedIcon} accessibleLabel={label} size={size} style={style} pressed={pressed} disabled={disabled} onClick={()=>{setPressed(!pressed);setLog('onClick executado')}}/>} controls={<><SelectCtl label="size" value={size} options={['Medium','Large']} onChange={setSize}/><SelectCtl label="style" value={style} options={['Primary','Secondary','Ghost']} onChange={setStyle}/><label>icon<select value={icon} onChange={e=>setIcon(e.target.value as IconName)}>{iconNames.map(n=><option key={n}>{n}</option>)}</select></label><TextCtl label="accessibleLabel" value={label} onChange={setLabel}/><CheckCtl label="pressed (toggle usage)" value={pressed} onChange={setPressed}/><CheckCtl label="disabled" value={disabled} onChange={setDisabled}/></>} code={`<IconButton\n  icon={<Icon name="${icon}" size={20} />}\n  accessibleLabel="${label}"\n  size="${size}"\n  style="${style}"\n  pressed={${pressed}}\n/>`} stateLab={<States>{(['Default','Hover','Focused','Pressed','Disabled'] as const).map(s=><StateItem key={s} label={s}><IconButton icon={<Icon name="Bell" size={20}/>} accessibleLabel="Notificações" state={s}/></StateItem>)}</States>} eventLog={log}/>}
function InputPage(){const spec=componentSpecs['input-field'];const[size,setSize]=useState<'Medium'|'Large'>('Medium');const[state,setState]=useState<any>('Default');const[label,setLabel]=useState('Nome completo');const[helper,setHelper]=useState('Como aparece no documento');const[value,setValue]=useState('Digite seu nome');const[showLabel,setShowLabel]=useState(true);const[showHelper,setShowHelper]=useState(true);const[showIcon,setShowIcon]=useState(false);
 return <ComponentPage spec={spec} preview={<InputField size={size} state={state} label={label} helper={helper} value={value} showLabel={showLabel} showHelper={showHelper} showLeadingIcon={showIcon} icon={<Icon name="User" size={20}/>} onChange={setValue}/>} controls={<><SelectCtl label="size" value={size} options={['Medium','Large']} onChange={setSize}/><SelectCtl label="state" value={state} options={['Default','Hover','Focused','Filled','Error','Disabled']} onChange={setState}/><TextCtl label="label" value={label} onChange={setLabel}/><TextCtl label="value" value={value} onChange={setValue}/><TextCtl label="helper" value={helper} onChange={setHelper}/><CheckCtl label="showLabel" value={showLabel} onChange={setShowLabel}/><CheckCtl label="showHelper" value={showHelper} onChange={setShowHelper}/><CheckCtl label="showLeadingIcon" value={showIcon} onChange={setShowIcon}/></>} code={`<InputField\n  label="${label}"\n  helper="${helper}"\n  value={value}\n  size="${size}"\n  state="${state}"\n  onChange={setValue}\n/>`} stateLab={<States>{(['Default','Hover','Focused','Filled','Error','Disabled'] as const).map(s=><StateItem key={s} label={s}><InputField state={s} value="Digite seu nome"/></StateItem>)}</States>}/>}
function TextareaPage(){const spec=componentSpecs.textarea;const[rows,setRows]=useState<'3'|'5'>('3');const[state,setState]=useState<any>('Default');const[label,setLabel]=useState('Motivo da consulta');const[helper,setHelper]=useState('Até 500 caracteres');const[value,setValue]=useState('Descreva o que você está sentindo');const[showLabel,setShowLabel]=useState(true);const[showHelper,setShowHelper]=useState(true);
 return <ComponentPage spec={spec} preview={<Textarea rows={rows} state={state} label={label} helper={helper} value={value} showLabel={showLabel} showHelper={showHelper} onChange={setValue}/>} controls={<><SelectCtl label="rows" value={rows} options={['3','5']} onChange={setRows}/><SelectCtl label="state" value={state} options={['Default','Hover','Focused','Filled','Error','Disabled']} onChange={setState}/><TextCtl label="label" value={label} onChange={setLabel}/><TextCtl label="value" value={value} onChange={setValue}/><TextCtl label="helper" value={helper} onChange={setHelper}/><CheckCtl label="showLabel" value={showLabel} onChange={setShowLabel}/><CheckCtl label="showHelper" value={showHelper} onChange={setShowHelper}/></>} code={`<Textarea rows="${rows}" state="${state}" label="${label}" helper="${helper}" value={value} onChange={setValue} />`} stateLab={<States>{(['Default','Hover','Focused','Filled','Error','Disabled'] as const).map(s=><StateItem key={s} label={s}><Textarea state={s}/></StateItem>)}</States>}/>}
function SelectPage(){const spec=componentSpecs.select;const[size,setSize]=useState<'Medium'|'Large'>('Medium');const[state,setState]=useState<any>('Default');const[label,setLabel]=useState('Especialidade');const[helper,setHelper]=useState('Escolha uma opção');const[value,setValue]=useState('Selecione');const[expanded,setExpanded]=useState(false);const[activeIndex,setActiveIndex]=useState(0);const[log,setLog]=useState('');
 const exampleOptions=['Psicologia','Nutrição','Clínica geral','Dermatologia'];const listId=`select-list-${useId().replace(/:/g,'')}`;const triggerRef=useRef<HTMLButtonElement>(null);const optionRefs=useRef<Array<HTMLButtonElement|null>>([])
 useEffect(()=>{if(expanded) optionRefs.current[activeIndex]?.focus()},[expanded,activeIndex])
 const selectedIndex=Math.max(0,exampleOptions.indexOf(value))
 const open=(index=selectedIndex)=>{if(state==='Disabled')return;setActiveIndex(index);setExpanded(true);setLog('Lista aberta')}
 const close=(returnFocus=true)=>{setExpanded(false);setLog('Lista fechada');if(returnFocus)requestAnimationFrame(()=>triggerRef.current?.focus())}
 const choose=(option:string)=>{setValue(option);setState('Filled');setExpanded(false);setLog(`Selecionado: ${option}`);requestAnimationFrame(()=>triggerRef.current?.focus())}
 const triggerKey=(e:React.KeyboardEvent<HTMLButtonElement>)=>{if(state==='Disabled')return;if(e.key==='ArrowDown'){e.preventDefault();open(selectedIndex)}else if(e.key==='ArrowUp'){e.preventDefault();open(expanded?activeIndex:exampleOptions.length-1)}else if(e.key==='Escape'&&expanded){e.preventDefault();close()}}
 const optionKey=(e:React.KeyboardEvent<HTMLButtonElement>,index:number)=>{if(e.key==='ArrowDown'){e.preventDefault();setActiveIndex((index+1)%exampleOptions.length)}else if(e.key==='ArrowUp'){e.preventDefault();setActiveIndex((index-1+exampleOptions.length)%exampleOptions.length)}else if(e.key==='Home'){e.preventDefault();setActiveIndex(0)}else if(e.key==='End'){e.preventDefault();setActiveIndex(exampleOptions.length-1)}else if(e.key==='Enter'||e.key===' '){e.preventDefault();choose(exampleOptions[index])}else if(e.key==='Escape'){e.preventDefault();close()}else if(e.key==='Tab'){setExpanded(false)}}
 const visualState=expanded&&state==='Default'?'Focused':state
 return <ComponentPage spec={spec}
  preview={<div className="select-demo-wrap">
   <SelectField triggerRef={triggerRef} controlsId={listId} size={size} state={visualState} label={label} helper={helper} showHelper={!expanded} value={value} expanded={expanded} icon={<Icon name="Chevron Down" size={20}/>} onTrigger={()=>expanded?close(false):open()} onKeyDown={triggerKey}/>
   {expanded&&state!=='Disabled'?<div id={listId} className="select-demo-options" role="listbox" aria-label={`${label} — opções de exemplo`}>{exampleOptions.map((option,index)=><SelectOption optionId={`${listId}-${index}`} optionRef={el=>{optionRefs.current[index]=el}} label={option} selected={value===option} state={'Default'} key={option} onSelect={()=>choose(option)} onKeyDown={e=>optionKey(e,index)}/>)}</div>:null}
  </div>}
  controls={<><SelectCtl label="size" value={size} options={['Medium','Large']} onChange={setSize}/><SelectCtl label="state" value={state} options={['Default','Hover','Focused','Filled','Error','Disabled']} onChange={v=>{setExpanded(false);setState(v)}}/><TextCtl label="label" value={label} onChange={setLabel}/><TextCtl label="value" value={value} onChange={setValue}/><TextCtl label="helper" value={helper} onChange={setHelper}/></>}
  code={`const exampleOptions = ['Psicologia', 'Nutrição', 'Clínica geral', 'Dermatologia']\n\n<SelectField\n  label="${label}"\n  helper="${helper}"\n  value="${value}"\n  size="${size}"\n  state="${state}"\n  expanded={isOpen}\n  controlsId="specialty-list"\n  onTrigger={() => setIsOpen(v => !v)}\n/>\n{isOpen && <div id="specialty-list" role="listbox">\n  {exampleOptions.map(option => (\n    <SelectOption\n      key={option}\n      label={option}\n      selected={value === option}\n      onSelect={() => setValue(option)}\n    />\n  ))}\n</div>}\n// Example data only; product option data remains consumer-defined.`}
  stateLab={<><h3>Trigger states</h3><States>{(['Default','Hover','Focused','Filled','Error','Disabled'] as const).map(s=><StateItem key={s} label={s}><SelectField state={s} value={s==='Filled'?'Psicologia':'Selecione'} icon={<Icon name="Chevron Down" size={20}/>} /></StateItem>)}</States><h3>Select / Option</h3><States>{(['Default','Hover','Focused','Disabled'] as const).flatMap(st=>[false,true].map(sel=><StateItem key={`${st}-${sel}`} label={`${sel?'Selected':'Unselected'} / ${st}`}><SelectOption label="Opção" selected={sel} state={st}/></StateItem>))}</States></>}
  eventLog={`${log}${log?' · ':''}Psicologia, Nutrição, Clínica geral e Dermatologia são example data; não fazem parte do contrato de produto.`}
 />}


function CheckboxPage(){const spec=componentSpecs.checkbox;const[selected,setSelected]=useState<'False'|'True'|'Indeterminate'>('False');const[state,setState]=useState<any>('Default');const[label,setLabel]=useState('Aceito os termos');
 return <ComponentPage spec={spec} preview={<Checkbox label={label} selected={selected} state={state} onSelectedChange={setSelected}/>} controls={<><SelectCtl label="selected" value={selected} options={['False','True','Indeterminate']} onChange={setSelected}/><SelectCtl label="state" value={state} options={['Default','Hover','Focused','Disabled']} onChange={setState}/><TextCtl label="label" value={label} onChange={setLabel}/></>} code={`<Checkbox label="${label}" selected="${selected}" state="${state}" onSelectedChange={setSelected} />`} stateLab={<States>{(['Default','Hover','Focused','Disabled'] as const).flatMap(s=>['False','True','Indeterminate'].map(sel=><StateItem key={s+sel} label={`${sel} / ${s}`}><Checkbox selected={sel as any} state={s}/></StateItem>))}</States>}/>}
function RadioPage(){const spec=componentSpecs.radio;const[state,setState]=useState<any>('Default');const[label,setLabel]=useState('Psicologia');const[groupLabel,setGroupLabel]=useState('Opções');const[groupValue,setGroupValue]=useState('option-a');
 const exampleOptions=[{label:'Opção A',value:'option-a'},{label:'Opção B',value:'option-b'},{label:'Opção C',value:'option-c'}]
 return <ComponentPage spec={spec}
  preview={<RadioGroup label={groupLabel} options={exampleOptions} value={groupValue} onValueChange={setGroupValue}/>}
  controls={<><TextCtl label="group label · composition" value={groupLabel} onChange={setGroupLabel}/><SelectCtl label="selected example" value={groupValue} options={['option-a','option-b','option-c']} onChange={setGroupValue}/><SelectCtl label="item state · reference" value={state} options={['Default','Hover','Focused','Disabled']} onChange={setState}/><TextCtl label="item label · reference" value={label} onChange={setLabel}/></>}
  code={`const options = [
  { label: 'Opção A', value: 'option-a' },
  { label: 'Opção B', value: 'option-b' },
  { label: 'Opção C', value: 'option-c' },
]

<RadioGroup
  label="${groupLabel}"
  options={options}
  value="${groupValue}"
  onValueChange={setValue}
/>

// Radio continua sendo o item visual documentado no Figma:
<Radio label="${label}" state="${state}" />`}
  stateLab={<States>{(['Default','Hover','Focused','Disabled'] as const).flatMap(s=>[false,true].map(sel=><StateItem key={s+String(sel)} label={`${sel?'Selected':'Unselected'} / ${s}`}><Radio selected={sel} state={s}/></StateItem>))}</States>}
  eventLog={`Radio Group · seleção exclusiva = ${groupValue}. As labels Opção A/B/C são EXAMPLE DATA, não dados de produto.`}
 />}

function SwitchPage(){const spec=componentSpecs.switch;const[checked,setChecked]=useState(false);const[state,setState]=useState<any>('Default');const[label,setLabel]=useState('Ativar câmera');const[pending,setPending]=useState(false);const[failNext,setFailNext]=useState(false);const[log,setLog]=useState('');
 const persist=(next:boolean)=>{if(pending||state==='Disabled')return;const previous=checked;setChecked(next);setPending(true);setLog(`Atualização otimista: checked = ${next}. Persistindo…`);window.setTimeout(()=>{if(failNext){setChecked(previous);setFailNext(false);setLog(`Falha simulada de persistência: rollback para checked = ${previous}. A copy/feedback de erro pertence ao consumidor e não está definida no contrato do Switch.`)}else{setLog(`Persistência simulada concluída: checked = ${next}.`)}setPending(false)},650)}
 const consumerState=pending?'Disabled':state
 const behaviorLab=<div className="behavior-lab"><div><strong>Persistência controlada pelo consumidor</strong><p>O Switch não ganha Loading/Error. Durante a persistência, o consumidor usa <code>State=Disabled</code>; em falha, restaura o valor anterior.</p></div><div className="behavior-lab-actions"><Button label={failNext?'Falha armada':'Simular falha na próxima alteração'} style="Secondary" size="Medium" disabled={failNext||pending} onClick={()=>setFailNext(true)}/><span className="meta-chip">{pending?'Processing · consumer':'Idle'}</span></div></div>
 return <ComponentPage spec={spec}
  preview={<Switch checked={checked} state={consumerState} label={label} onCheckedChange={persist}/>}
  controls={<><CheckCtl label="checked" value={checked} onChange={setChecked}/><SelectCtl label="state" value={state} options={['Default','Hover','Focused','Disabled']} onChange={setState}/><TextCtl label="label" value={label} onChange={setLabel}/></>}
  code={`function CameraSetting(){\n  const [checked, setChecked] = useState(false)\n  const [saving, setSaving] = useState(false)\n\n  async function handleChange(next: boolean){\n    const previous = checked\n    setChecked(next) // optimistic update\n    setSaving(true)\n    try {\n      await persistSetting(next) // consumer integration\n    } catch {\n      setChecked(previous) // rollback\n      // Show feedback outside Switch; copy is product-defined.\n    } finally {\n      setSaving(false)\n    }\n  }\n\n  return (\n    <Switch\n      checked={checked}\n      label="${label}"\n      state={saving ? "Disabled" : "${state}"}\n      onCheckedChange={handleChange}\n    />\n  )\n}`}
  stateLab={<States>{(['Default','Hover','Focused','Disabled'] as const).flatMap(s=>[false,true].map(v=><StateItem key={s+String(v)} label={`${v?'On':'Off'} / ${s}`}><Switch checked={v} state={s}/></StateItem>))}</States>}
  behaviorLab={behaviorLab}
  eventLog={log||`checked = ${checked}`}
 />}

function BadgePage(){const spec=componentSpecs.badge;const[size,setSize]=useState<'Small'|'Medium'>('Small');const[tone,setTone]=useState<any>('Brand');const[label,setLabel]=useState('Confirmado');
 return <ComponentPage spec={spec} preview={<Badge size={size} tone={tone} label={label}/>} controls={<><SelectCtl label="size" value={size} options={['Small','Medium']} onChange={setSize}/><SelectCtl label="tone" value={tone} options={['Brand','Success','Warning','Danger','Info','Neutral']} onChange={setTone}/><TextCtl label="label" value={label} onChange={setLabel}/></>} code={`<Badge label="${label}" size="${size}" tone="${tone}" />`} stateLab={<States>{(['Brand','Success','Warning','Danger','Info','Neutral'] as const).map(t=><StateItem key={t} label={t}><Badge tone={t}/></StateItem>)}</States>}/>}
function AvatarPage(){const spec=componentSpecs.avatar;const[size,setSize]=useState<'Small'|'Medium'|'Large'>('Small');const[status,setStatus]=useState<any>('Online');const[initials,setInitials]=useState('ML');
 return <ComponentPage spec={spec} preview={<Avatar size={size} status={status} initials={initials}/>} controls={<><SelectCtl label="size" value={size} options={['Small','Medium','Large']} onChange={setSize}/><SelectCtl label="status" value={status} options={['Online','Away','Offline']} onChange={setStatus}/><TextCtl label="initials" value={initials} onChange={setInitials}/></>} code={`<Avatar initials="${initials}" size="${size}" status="${status}" />`} stateLab={<States>{(['Small','Medium','Large'] as const).flatMap(s=>['Online','Away','Offline'].map(st=><StateItem key={s+st} label={`${s} / ${st}`}><Avatar size={s} status={st as any}/></StateItem>))}</States>}/>}
function TabsPage(){const spec=componentSpecs.tabs;const[selected,setSelected]=useState(false);const[state,setState]=useState<any>('Default');const[label,setLabel]=useState('Resumo');
 return <ComponentPage spec={spec} preview={<TabItem label={label} selected={selected} state={state} onSelect={()=>setSelected(true)}/>} controls={<><CheckCtl label="selected" value={selected} onChange={setSelected}/><SelectCtl label="state" value={state} options={['Default','Hover','Focused','Disabled']} onChange={setState}/><TextCtl label="label" value={label} onChange={setLabel}/></>} code={`<TabItem label="${label}" selected={${selected}} state="${state}" onSelect={() => setSelected(true)} />`} stateLab={<States>{(['Default','Hover','Focused','Disabled'] as const).flatMap(s=>[false,true].map(v=><StateItem key={s+String(v)} label={`${v?'Selected':'Unselected'} / ${s}`}><TabItem selected={v} state={s}/></StateItem>))}</States>} eventLog={selected?'Tab item selecionado. Labels/painéis adicionais não estão definidos no Figma.':'Clique para selecionar o Tab Item.'}/>}
function AlertPage(){const spec=componentSpecs.alert;const[tone,setTone]=useState<any>('Info');const[action,setAction]=useState(false);const[title,setTitle]=useState('Conexão instável');const[body,setBody]=useState('A qualidade do vídeo pode oscilar por alguns instantes.');const[actionLabel,setActionLabel]=useState('Tentar novamente');const[log,setLog]=useState('');
 return <ComponentPage spec={spec} preview={<Alert tone={tone} action={action} title={title} body={body} actionLabel={actionLabel} onAction={()=>setLog('Ação do Alert executada')}/>} controls={<><SelectCtl label="tone" value={tone} options={['Info','Success','Warning','Danger']} onChange={setTone}/><CheckCtl label="action" value={action} onChange={setAction}/><TextCtl label="title" value={title} onChange={setTitle}/><TextCtl label="body" value={body} onChange={setBody}/><TextCtl label="actionLabel" value={actionLabel} onChange={setActionLabel}/></>} code={`<Alert tone="${tone}" action={${action}} title="${title}" body="${body}" actionLabel="${actionLabel}" onAction={() => {}} />`} stateLab={<States>{(['Info','Success','Warning','Danger'] as const).map(t=><StateItem key={t} label={t}><Alert tone={t}/></StateItem>)}</States>} eventLog={log}/>}
function DoctorPage(){const spec=componentSpecs['doctor-card'];const[availability,setAvailability]=useState<any>('Available');const[featured,setFeatured]=useState(false);const[name,setName]=useState('Dra. Marina Lopes');const[nextSlot,setNextSlot]=useState('Hoje, 16:30');const[rating,setRating]=useState('★ 4,9 · 128 avaliações');const[specialty,setSpecialty]=useState('Psicologia · CRP 06/123456');
 return <ComponentPage spec={spec} preview={<DoctorCard availability={availability} featured={featured} name={name} nextSlot={nextSlot} rating={rating} specialty={specialty}/>} controls={<><SelectCtl label="availability" value={availability} options={['Available','Busy','Offline']} onChange={setAvailability}/><CheckCtl label="featured" value={featured} onChange={setFeatured}/><TextCtl label="name" value={name} onChange={setName}/><TextCtl label="specialty" value={specialty} onChange={setSpecialty}/><TextCtl label="rating" value={rating} onChange={setRating}/><TextCtl label="nextSlot" value={nextSlot} onChange={setNextSlot}/></>} code={`<DoctorCard availability="${availability}" featured={${featured}} name="${name}" specialty="${specialty}" rating="${rating}" nextSlot="${nextSlot}" />`} stateLab={<States>{(['Available','Busy','Offline'] as const).flatMap(a=>[false,true].map(f=><StateItem key={a+String(f)} label={`${a} / Featured ${f}`}><DoctorCard availability={a} featured={f}/></StateItem>))}</States>}/>}
function AppointmentPage(){const spec=componentSpecs['appointment-card'];const[status,setStatus]=useState<any>('Upcoming');const[action,setAction]=useState(false);const[title,setTitle]=useState('Psicologia');const[professional,setProfessional]=useState('Dra. Marina Lopes');const[date,setDate]=useState('12 ago · 16:30');const[actionLabel,setActionLabel]=useState('Entrar na consulta');const[log,setLog]=useState('');
 return <ComponentPage spec={spec} preview={<AppointmentCard status={status} action={action} title={title} professional={professional} date={date} actionLabel={actionLabel} onAction={()=>setLog('Ação de consulta executada')}/>} controls={<><SelectCtl label="status" value={status} options={['Upcoming','Today','Completed','Cancelled']} onChange={setStatus}/><CheckCtl label="action" value={action} onChange={setAction}/><TextCtl label="title" value={title} onChange={setTitle}/><TextCtl label="professional" value={professional} onChange={setProfessional}/><TextCtl label="date" value={date} onChange={setDate}/><TextCtl label="actionLabel" value={actionLabel} onChange={setActionLabel}/></>} code={`<AppointmentCard status="${status}" action={${action}} title="${title}" professional="${professional}" date="${date}" actionLabel="${actionLabel}" />`} stateLab={<States>{(['Upcoming','Today','Completed','Cancelled'] as const).map(s=><StateItem key={s} label={s}><AppointmentCard status={s}/></StateItem>)}</States>} eventLog={log||((status==='Completed'||status==='Cancelled')&&action?'Action=True foi suprimido conforme a documentação da página.':'')}/>}
function DevicePage(){const spec=componentSpecs['device-check-row'];const[device,setDevice]=useState<any>('Camera');const[status,setStatus]=useState<any>('Checking');const[label,setLabel]=useState('Câmera');const[detail,setDetail]=useState('Verificando acesso…');
 return <ComponentPage spec={spec} preview={<DeviceCheckRow device={device} status={status} label={label} detail={detail}/>} controls={<><SelectCtl label="device" value={device} options={['Camera','Microphone','Connection']} onChange={v=>{setDevice(v);setLabel({Camera:'Câmera',Microphone:'Microfone',Connection:'Conexão'}[v])}}/><SelectCtl label="status" value={status} options={['Checking','Ready','Warning','Error']} onChange={setStatus}/><TextCtl label="label" value={label} onChange={setLabel}/><TextCtl label="detail" value={detail} onChange={setDetail}/></>} code={`<DeviceCheckRow device="${device}" status="${status}" label="${label}" detail="${detail}" />`} stateLab={<States>{(['Camera','Microphone','Connection'] as const).flatMap(d=>['Checking','Ready','Warning','Error'].map(s=><StateItem key={d+s} label={`${d} / ${s}`}><DeviceCheckRow device={d} status={s as any}/></StateItem>))}</States>}/>}
function FacePage(){const spec=componentSpecs['face-guidance-status'];const[status,setStatus]=useState<any>('Scanning');const[layout,setLayout]=useState<any>('Compact');const[title,setTitle]=useState('Procurando seu rosto');const[detail,setDetail]=useState('Olhe para a câmera');
 return <ComponentPage spec={spec} preview={<FaceGuidanceStatus status={status} layout={layout} title={title} detail={detail}/>} controls={<><SelectCtl label="status" value={status} options={['Scanning','Ready','Warning','Error']} onChange={setStatus}/><SelectCtl label="layout" value={layout} options={['Compact','Expanded']} onChange={setLayout}/><TextCtl label="title" value={title} onChange={setTitle}/><TextCtl label="detail" value={detail} onChange={setDetail}/></>} code={`<FaceGuidanceStatus status="${status}" layout="${layout}" title="${title}" detail="${detail}" />`} stateLab={<States>{(['Scanning','Ready','Warning','Error'] as const).flatMap(s=>['Compact','Expanded'].map(l=><StateItem key={s+l} label={`${s} / ${l}`}><FaceGuidanceStatus status={s} layout={l as any}/></StateItem>))}</States>}/>}
function CameraPage(){const spec=componentSpecs['camera-guidance-overlay'];const[status,setStatus]=useState<any>('Tracking');const[controls,setControls]=useState(false);const[title,setTitle]=useState('Centralize seu rosto');const[detail,setDetail]=useState('Mantenha os olhos na altura indicada');const[log,setLog]=useState('');
 return <ComponentPage spec={spec} preview={<CameraGuidanceOverlay status={status} controls={controls} title={title} detail={detail} onCamera={()=>setLog('Câmera acionada')} onMicrophone={()=>setLog('Microfone acionado')} onExit={()=>setLog('Sair acionado')}/>} controls={<><SelectCtl label="status" value={status} options={['Tracking','Ready','Warning','Error']} onChange={setStatus}/><CheckCtl label="controls" value={controls} onChange={setControls}/><TextCtl label="title" value={title} onChange={setTitle}/><TextCtl label="detail" value={detail} onChange={setDetail}/></>} code={`<CameraGuidanceOverlay status="${status}" controls={${controls}} title="${title}" detail="${detail}" onCamera={() => {}} onMicrophone={() => {}} onExit={() => {}} />`} stateLab={<States>{(['Tracking','Ready','Warning','Error'] as const).map(s=><StateItem key={s} label={s}><CameraGuidanceOverlay status={s}/></StateItem>)}</States>} eventLog={log} previewClass="video"/>}
function CallPage(){const spec=componentSpecs['call-control'];const[tone,setTone]=useState<any>('Neutral');const[state,setState]=useState<any>('Default');const[label,setLabel]=useState('Microfone');const[activeLabel,setActiveLabel]=useState('');const[icon,setIcon]=useState<IconName>('Mic');const[activeIcon,setActiveIcon]=useState<IconName>('Mic Off');const[log,setLog]=useState('');
 const active=state==='Active'
 return <ComponentPage spec={spec} preview={<div style={tone==='Inverse'?{background:'var(--color-bg-video)',padding:24,borderRadius:12}:{}}><CallControl tone={tone} state={state} label={label} activeLabel={activeLabel} icon={<Icon name={icon}/>} activeIcon={<Icon name={activeIcon}/>} onActiveChange={v=>{setState(v?'Active':'Default');setLog(`Active = ${v}`)}} onPress={()=>setLog('Danger onPress executado')}/></div>} controls={<><SelectCtl label="tone" value={tone} options={['Neutral','Danger','Inverse']} onChange={setTone}/><SelectCtl label="state" value={state} options={['Default','Active','Focused','Disabled']} onChange={setState}/><TextCtl label="label" value={label} onChange={setLabel}/><TextCtl label="activeLabel — Figma gap" value={activeLabel} onChange={setActiveLabel}/><SelectCtl label="icon" value={icon} options={iconNames} onChange={setIcon}/><SelectCtl label="activeIcon" value={activeIcon} options={iconNames} onChange={setActiveIcon}/></>} code={`<CallControl\n  tone="${tone}"\n  state="${state}"\n  label="${label}"\n  activeLabel="${activeLabel}"\n  icon={<Icon name="${icon}" />}\n  activeIcon={<Icon name="${activeIcon}" />}\n  onActiveChange={() => {}}\n/>`} stateLab={<States>{(['Default','Active','Focused','Disabled'] as const).map(s=><StateItem key={s} label={s}><CallControl state={s} activeLabel=""/></StateItem>)}</States>} eventLog={active&&!activeLabel?'UNKNOWN — Active exige rótulo alternativo, mas a copy não está definida no Figma. Preencha activeLabel para validar.':log}/>}
function HeaderPage(){const spec=componentSpecs['desktop-header'];const[active,setActive]=useState<any>('Início');const[log,setLog]=useState('');
 return <ComponentPage spec={spec} preview={<DesktopHeader active={active} onActiveChange={v=>{setActive(v);setLog(`Rota ativa: ${v}`)}} onNotifications={()=>setLog('Notificações acionadas')}/>} controls={<SelectCtl label="active" value={active} options={['Início','Especialistas','Agenda','Documentos']} onChange={setActive}/>} code={`<DesktopHeader active="${active}" onActiveChange={setActive} onNotifications={() => {}} />`} eventLog={log}/>}
const pages:Record<string,React.FC>={'button':ButtonPage,'button-destructive':DestructivePage,'icon-button':IconButtonPage,'input-field':InputPage,'textarea':TextareaPage,'select':SelectPage,'checkbox':CheckboxPage,'radio':RadioPage,'switch':SwitchPage,'badge':BadgePage,'avatar':AvatarPage,'tabs':TabsPage,'alert':AlertPage,'doctor-card':DoctorPage,'appointment-card':AppointmentPage,'device-check-row':DevicePage,'face-guidance-status':FacePage,'camera-guidance-overlay':CameraPage,'call-control':CallPage,'desktop-header':HeaderPage}
export function ComponentPlayground({id}:{id:string}){const Page=pages[id];return Page?<Page/>:null}
