export type PropRow={name:string;type:string;defaultValue:string;notes?:string}
export type ComponentSpec={
 id:string;name:string;figma:string;description:string;figmaProps:PropRow[];anatomy:string[];usage:string;dont:string;behavior:string;content:string;accessibility:string;keyboard:string;responsive:string;tokens:string[];edgeCases:string;dependencies:string;changelog:string;parity?:{status:'MATCH'|'MISMATCH'|'UNKNOWN';note:string}[]
}
export const nav:[string,[string,string][]][]=[
['Overview',[['overview','Overview'],['getting-started','Getting Started'],['components-index','Components Index']]],
['Foundations',[['foundations-color','Color'],['foundations-type','Typography'],['foundations-space','Spacing & Radius'],['foundations-elevation','Elevation']]],
['Components · Actions',[['button','Button'],['button-destructive','Button Destructive'],['icon-button','Icon Button']]],
['Components · Forms',[['input-field','Input Field'],['textarea','Textarea'],['select','Select'],['checkbox','Checkbox'],['radio','Radio'],['switch','Switch']]],
['Components · Feedback',[['badge','Badge'],['alert','Alert']]],
['Components · Navigation',[['tabs','Tabs'],['desktop-header','Desktop Header']]],
['Components · Identity',[['avatar','Avatar']]],
['Components · Clinical',[['doctor-card','Doctor Card'],['appointment-card','Appointment Card'],['device-check-row','Device Check Row'],['face-guidance-status','Face Guidance Status'],['camera-guidance-overlay','Camera Guidance Overlay'],['call-control','Call Control']]],
['Assets',[['icons','Icons']]],
['Patterns',[['teleconsultation','Teleconsultation'],['camera-face-guidance','Camera & Face Guidance']]],
['Guidelines',[['accessibility','Accessibility'],['content-clinical','Content & Clinical Language'],['responsive','Responsive Layout'],['edge-cases','Edge Case Lab']]],
['System',[['governance','Governance & Contribution'],['releases','Releases & Changelog']]]
]
const unknown='UNKNOWN — NEEDS DEFINITION'
export const componentSpecs:Record<string,ComponentSpec>={
'button':{id:'button',name:'Button',figma:'23:2',description:'Aciona tarefas e decisões. Use Primary para a ação principal da tela, Secondary para suporte e Ghost em barras ou contextos de baixa ênfase.',
figmaProps:[{name:'label',type:'string',defaultValue:'Continuar'},{name:'showIcon',type:'boolean',defaultValue:'false'},{name:'icon',type:'INSTANCE_SWAP / ReactNode',defaultValue:'private placeholder'},{name:'size',type:'Medium | Large',defaultValue:'Medium'},{name:'style',type:'Primary | Secondary | Ghost',defaultValue:'Primary'},{name:'state',type:'Default | Hover | Focused | Pressed | Disabled',defaultValue:'Default'}],
anatomy:['Container / button target','Optional icon slot','Label'],usage:'Ações que executam uma tarefa clara no contexto atual.',dont:'Navegação entre páginas, status passivo ou mais de uma ação Primary na mesma região.',
behavior:'Default evolui para Hover, Focused e Pressed conforme entrada. Loading/progress não é variante v1: durante ação assíncrona, o consumidor bloqueia repetição e preserva largura/contexto; qualquer indicador de progresso precisa de padrão próprio.',content:'Verbo + objeto, preferencialmente de 1 a 3 palavras. Até duas ações lado a lado. Rótulos longos devem ser reescritos.',accessibility:'Alvo mínimo de 44 px, foco visível e ordem de tabulação lógica. Disabled deriva de State=Disabled.',keyboard:'Botão nativo: Tab para foco; Enter/Espaço para ativar.',responsive:'Em mobile pode ocupar a largura disponível; não reduza o alvo abaixo de 44 px.',tokens:['color/action/primary/default','color/action/primary/hover','color/action/primary/pressed','color/border/focus','size/control/md','size/control/lg','radius/md'],edgeCases:'Processamento assíncrono não adiciona prop loading silenciosamente. Copy de progresso: '+unknown+'.',dependencies:'Icon slot usa ícone semântico do Vellora quando habilitado; progresso assíncrono pertence ao consumidor.',changelog:'2.0.0 · contrato de loading clarificado e Playground alinhado às 30 variantes.',parity:[{status:'MATCH',note:'Playground usa somente Size × Style × State e propriedades reais do Figma; sem prop disabled/loading paralela.'}]},

'button-destructive':{id:'button-destructive',name:'Button Destructive',figma:'25:39',description:'Para ações irreversíveis ou de alto impacto, como cancelar uma consulta ou remover dados.',
figmaProps:[{name:'label',type:'string',defaultValue:'Cancelar consulta'},{name:'showIcon',type:'boolean',defaultValue:'false'},{name:'icon',type:'INSTANCE_SWAP / ReactNode',defaultValue:'private placeholder'},{name:'size',type:'Medium | Large',defaultValue:'Medium'},{name:'state',type:'Default | Hover | Focused | Pressed | Disabled',defaultValue:'Default'}],
anatomy:['Destructive button target','Optional icon slot','Consequence label'],usage:'Exclusão, cancelamento definitivo ou perda relevante de dados.',dont:'Voltar, fechar, descartar filtro ou ações reversíveis de baixo impacto.',
behavior:'Exija confirmação quando o efeito não puder ser desfeito. Durante processamento, State=Disabled bloqueia repetição; loading não é variante desta família. Em falha, preserve contexto e explique recuperação.',content:'Nomeie a consequência, como “Cancelar consulta”; nunca apenas “Confirmar”.',accessibility:'Alvo de 44 px e foco funcional. Uma ação destrutiva por contexto.',keyboard:'Botão nativo: Tab; Enter/Espaço.',responsive:'Mantenha separação da ação principal e alvo mínimo.',tokens:['color/action/destructive/default','color/action/destructive/hover','color/action/destructive/pressed','color/border/focus','size/control/md','size/control/lg','radius/md'],edgeCases:'Dados parcialmente salvos, cobrança iniciada e consulta em andamento exigem mensagem específica do fluxo.',dependencies:'Confirmação e progresso pertencem ao consumidor.',changelog:'2.0.0 · Playground cobre as 10 variantes sem prop disabled paralela.',parity:[{status:'MATCH',note:'Size × State e propriedades do Figma são reproduzidos diretamente.'}]},

'icon-button':{id:'icon-button',name:'Icon Button',figma:'26:157',description:'Ação compacta para barras, mídia e controles de teleconsulta. Accessible label é obrigatório; tooltip é uma composição separada quando o significado não for universal.',
figmaProps:[{name:'accessibleLabel',type:'string',defaultValue:'Abrir opções',notes:'Figma: Accessible label#26:2'},{name:'icon',type:'INSTANCE_SWAP / ReactNode',defaultValue:'private placeholder'},{name:'size',type:'Medium | Large',defaultValue:'Medium'},{name:'style',type:'Primary | Secondary | Ghost',defaultValue:'Primary'},{name:'state',type:'Default | Hover | Focused | Pressed | Disabled',defaultValue:'Default'}],
anatomy:['Circular touch target','Single semantic icon','Accessible label (non-visual property)'],usage:'Controles compactos de áudio, vídeo, navegação e barras de ferramentas.',dont:'Ações que precisam de explicação textual ou toggle persistente sem estado semântico próprio.',
behavior:'Pressed é estado transitório de interação, não estado persistente de toggle. Tooltip e loading não são props/variantes v1; quando necessários, entram por composição sem reduzir o alvo.',content:'Um único ícone; Accessible label obrigatório.',accessibility:'Alvo mínimo 44 px e foco visível. Accessible label fornece o nome do controle. Não use State=Pressed como aria-pressed persistente.',keyboard:'Tab para foco; Enter/Espaço para ativar.',responsive:'Não reduza o alvo; apenas o glifo varia entre 20 e 24 px.',tokens:['size/control/md','size/control/lg','size/icon/md','color/border/focus','radius/full'],edgeCases:'Tooltip visual ainda não é família publicada; use composição do consumidor quando necessário.',dependencies:'Depende de Icon library; o placeholder privado nunca permanece na instância final.',changelog:'2.0.0 · Accessible label sincronizado; pressed persistente removido da API do Playground.',parity:[{status:'MATCH',note:'API do Playground espelha Accessible label, Icon, Size, Style e State do component set.'}]},

'input-field':{id:'input-field',name:'Input Field',figma:'27:141',description:'Campo de entrada com rótulo persistente, ajuda contextual e feedback de erro. Não use placeholder como único rótulo.',
figmaProps:[{name:'helper',type:'string',defaultValue:'Como aparece no documento'},{name:'icon',type:'INSTANCE_SWAP / ReactNode',defaultValue:'private placeholder'},{name:'label',type:'string',defaultValue:'Nome completo'},{name:'showHelper',type:'boolean',defaultValue:'true'},{name:'showLabel',type:'boolean',defaultValue:'true'},{name:'showLeadingIcon',type:'boolean',defaultValue:'false'},{name:'size',type:'Medium | Large',defaultValue:'Medium'},{name:'state',type:'Default | Hover | Focused | Filled | Error | Disabled',defaultValue:'Default'},{name:'value',type:'string',defaultValue:'Digite seu nome'}],
anatomy:['Persistent label','Control container','Optional leading icon','Value','Helper / error message'],usage:'Entrada curta e livre, como nome, e-mail ou número de registro.',dont:'Respostas longas, escolha entre opções conhecidas ou dados que exigem formato especializado sem máscara.',
behavior:'Valide no blur ou envio; durante digitação, valide apenas formato útil. Filled significa conteúdo presente, não sucesso. Error preserva o valor e usa helper para causa/recuperação.',content:'Label persistente, exemplo apenas como apoio e ajuda objetiva. Comprimento é definido por campo.',accessibility:'IDs são únicos por instância; label, campo, ajuda e erro são associados programaticamente. Se Show label=False, o label continua como accessible name.',keyboard:'Comportamento nativo de input; Tab para entrada/saída; edição por teclado.',responsive:'Ocupa a largura disponível sem reduzir abaixo da leitura confortável.',tokens:['color/border/default','color/border/strong','color/border/focus','color/border/danger','color/bg/disabled','size/control/md','size/control/lg','radius/md','font/size/body-medium'],edgeCases:'Erro deve preservar valor. Limite de caracteres por campo: '+unknown+'.',dependencies:'Máscara, autocomplete, inputMode, maxLength e validação pertencem ao campo consumidor.',changelog:'2.0.0 · IDs únicos e semântica de label oculto corrigidos.',parity:[{status:'MATCH',note:'12 variantes Size × State e propriedades visuais do Figma estão cobertas; regras de campo específicas permanecem externas.'}]},

'textarea':{id:'textarea',name:'Textarea',figma:'28:127',description:'Entrada multilinha para sintomas, objetivos da consulta e observações. Use ajuda para orientar o nível de detalhe esperado.',
figmaProps:[{name:'helper',type:'string',defaultValue:'Até 500 caracteres'},{name:'label',type:'string',defaultValue:'Motivo da consulta'},{name:'rows',type:'3 | 5',defaultValue:'3'},{name:'showHelper',type:'boolean',defaultValue:'true'},{name:'showLabel',type:'boolean',defaultValue:'true'},{name:'state',type:'Default | Hover | Focused | Filled | Error | Disabled',defaultValue:'Default'},{name:'value',type:'string',defaultValue:'Descreva o que você está sentindo'}],
anatomy:['Persistent label','Multiline control','Value','Helper / error'],usage:'Sintomas, objetivos e observações que exigem múltiplas linhas.',dont:'Respostas curtas, códigos, datas ou seleção entre opções.',
behavior:'Rows=3/5 define altura inicial. Limite de caracteres e contador não são propriedades do component set v1; se o campo exigir maxLength, consumidor/configuração define limite e contador.',content:'Diga o nível de detalhe esperado. “500 caracteres” é EXAMPLE COPY e não define maxLength.',accessibility:'IDs únicos por instância; label e helper/erro associados. Se Show label=False, label permanece como accessible name.',keyboard:'Comportamento nativo de textarea. Tab entra/sai; Enter cria nova linha.',responsive:'Pode crescer verticalmente; não fixe altura de mensagem.',tokens:['color/border/default','color/border/strong','color/border/focus','color/border/danger','radius/md','font/size/body-medium'],edgeCases:'3/5 são alturas iniciais, não máximo. Limite real: '+unknown+'.',dependencies:'Contador/maxLength pertence à configuração do campo consumidor.',changelog:'2.0.0 · counter/maxLength deixaram de ser prometidos como API embutida; IDs únicos corrigidos.',parity:[{status:'MATCH',note:'12 variantes Rows × State reproduzidas; “500 caracteres” permanece exemplo, não regra de produto.'}]},

'select':{id:'select',name:'Select',figma:'29:103',description:'Escolha uma opção de uma lista. Prefira rótulos claros e mantenha o valor selecionado visível.',
figmaProps:[{name:'helper',type:'string',defaultValue:'Escolha uma opção'},{name:'icon',type:'INSTANCE_SWAP / ReactNode',defaultValue:'private placeholder'},{name:'label',type:'string',defaultValue:'Especialidade'},{name:'showHelper',type:'boolean',defaultValue:'true'},{name:'showLabel',type:'boolean',defaultValue:'true'},{name:'size',type:'Medium | Large',defaultValue:'Medium'},{name:'state',type:'Default | Hover | Focused | Filled | Error | Disabled',defaultValue:'Default'},{name:'value',type:'string',defaultValue:'Selecione'},{name:'option.label',type:'string',defaultValue:'Opção',notes:'Select / Option · node 310:78'},{name:'option.selected',type:'boolean',defaultValue:'false',notes:'Select / Option'},{name:'option.state',type:'Default | Hover | Focused | Disabled',defaultValue:'Default',notes:'Select / Option'}],
anatomy:['Persistent label','Trigger 320 px','Value','Icon slot / Chevron Down example','Helper / error','Select / Option · 44 px target','Selected marker · Icon/Check','Listbox container'],usage:'Escolha de uma opção em lista finita.',dont:'Duas opções binárias, entrada livre ou listas extensas que exigem busca.',
behavior:'Trigger: 12 variantes Size × State. Select / Option: 8 variantes Selected × State. Abrir pelo trigger; setas percorrem opções; Enter/Espaço seleciona; Escape fecha sem alterar. Ao selecionar, feche lista, atualize valor e devolva foco ao trigger.',content:'Label persistente e valor selecionado visível. Psicologia, Nutrição, Clínica geral e Dermatologia são EXAMPLE DATA do Playground, não dados de produto.',accessibility:'Trigger usa combobox, aria-expanded, aria-controls, accessible name e helper associado. Lista usa listbox; opções usam role=option + aria-selected; Check reforça seleção sem depender só de cor.',keyboard:'Trigger: ArrowDown/ArrowUp abre e posiciona foco; Escape fecha. Lista: ArrowUp/ArrowDown, Home/End, Enter/Espaço, Escape; seleção retorna foco ao trigger.',responsive:'No mobile, lista pode usar popover amplo, bottom sheet ou controle nativo conforme contexto; Option mantém 44 px.',tokens:['color/bg/surface','color/bg/brand-subtle','color/bg/disabled','color/text/primary','color/text/brand','color/text/disabled','color/border/default','color/border/focus','size/control/md','size/control/lg','size/icon/md','radius/md','spacing/4','spacing/12'],edgeCases:'Até 10 opções sem busca é referência documentada. Loading, vazio e sem resultados não têm conteúdo inventado.',dependencies:'Select / Option · Figma 310:78 + Icon/Chevron Down + Icon/Check. Dados de produto permanecem consumer-defined.',changelog:'2.0.0 · Playground cobre 12 variantes do trigger + 8 da Option; inventário atual contabiliza 235 variant nodes.',parity:[{status:'MATCH',note:'Trigger e Option estão materializados no Figma; demo aberta, seleção e teclado são funcionais, com example data explicitamente separada.'}]},

'checkbox':{id:'checkbox',name:'Checkbox',figma:'30:55',description:'Seleção múltipla ou consentimento. O estado indeterminado representa seleção parcial.',
figmaProps:[{name:'label',type:'string',defaultValue:'Aceito os termos'},{name:'selected',type:'False | True | Indeterminate',defaultValue:'False'},{name:'state',type:'Default | Hover | Focused | Disabled',defaultValue:'Default'}],
anatomy:['44 px control row','20 × 20 px checkbox box','14 px Inter Medium mark, centered on both axes','8 px gap','Label'],usage:'Seleção independente, múltiplas opções ou consentimento explícito.',dont:'Escolha exclusiva, configuração que produz efeito imediato ou aceite implícito.',
behavior:'Visual parity: unselected Hover mantém border/default; Focused usa border/focus 2 px; Selected e Indeterminate usam brand fill; Selected/Indeterminate Disabled usam surface white + border/brand + glyph disabled. Clique no controle ou label alterna seleção. Indeterminate representa apenas resumo parcial de grupo; consentimento nunca inicia marcado.',content:'Label afirma claramente o que será selecionado.',accessibility:'Agrupe opções relacionadas com nome de grupo e exponha checked/mixed.',keyboard:'Tab para foco; Espaço alterna o checkbox. Regra de Indeterminate em grupo: '+unknown+'.',responsive:'Preserve alvo de 44 px e permita quebra do label.',tokens:['size/control/md','color/border/default','color/border/brand','color/border/focus','radius/sm'],edgeCases:'A próxima ação de Indeterminate depende da regra do grupo, não definida no component set.',dependencies:'Group behavior quando usado como seleção coletiva.',changelog:'Baseline Vellora 1.0.'},
'radio':{id:'radio',name:'Radio',figma:'31:38',description:'Item de seleção exclusiva entre opções relacionadas. O comportamento exclusivo pertence à composição Radio Group.',
figmaProps:[{name:'label',type:'string',defaultValue:'Psicologia'},{name:'selected',type:'boolean',defaultValue:'false'},{name:'state',type:'Default | Hover | Focused | Disabled',defaultValue:'Default'}],
anatomy:['Radio item: 44 px interaction row','20 × 20 radio','Label','Radio Group composition: group label + 2–7 Radio items'],usage:'Uma única escolha entre opções relacionadas e mutuamente exclusivas.',dont:'Seleção múltipla, ação imediata independente ou lista longa.',
behavior:'Radio representa o item. O grupo mantém apenas uma opção selecionada. Setas movem e selecionam dentro do grupo; Tab entra e sai do conjunto. Só defina seleção inicial quando houver opção segura e neutra.',content:'Labels paralelos e comparáveis. O grupo deve ter nome/legend; labels e values são dados do produto.',accessibility:'Composição usa fieldset/radiogroup com nome do grupo; cada item expõe checked, posição no conjunto e tamanho do conjunto.',keyboard:'Tab entra/sai do grupo; ArrowUp/ArrowLeft selecionam a opção habilitada anterior; ArrowDown/ArrowRight selecionam a próxima.',responsive:'Empilhe opções quando não houver espaço para leitura horizontal.',tokens:['size/control/md','color/border/default','color/border/brand','color/border/focus'],edgeCases:'Recomendado 2 a 7 opções; acima disso avalie Select. Sem seleção inicial é permitido quando não houver opção segura/neutra.',dependencies:'Radio Group é composição documentada no Figma em 314:2 e não cria uma nova família/variant set.',changelog:'Baseline Vellora 1.0 · Radio Group composition formalizada em 18 ago 2026.',parity:[{status:'MATCH',note:'Radio item 31:38 + composição Radio Group 314:2 sincronizados. Dados Opção A/B/C são explicitamente example data.'}]},
'switch':{id:'switch',name:'Switch',figma:'32:38',description:'Ativa ou desativa uma configuração imediatamente. Use uma descrição que expresse o estado.',
figmaProps:[{name:'checked',type:'boolean',defaultValue:'false'},{name:'label',type:'string',defaultValue:'Ativar câmera'},{name:'state',type:'Default | Hover | Focused | Disabled',defaultValue:'Default'}],
anatomy:['44 px interaction row','44 × 24 track','20 × 20 thumb','12 px gap','Label'],usage:'Configuração binária aplicada imediatamente.',dont:'Respostas de formulário que dependem de Salvar, consentimento ou escolha entre mais de dois valores.',
behavior:'Checked atualiza imediatamente. Processing e persistence error não são variantes do Switch. Durante persistência, o consumidor bloqueia novas mudanças usando State=Disabled. Em falha, o consumidor restaura o valor anterior e apresenta feedback separado. O label descreve a configuração, não a ação.',content:'Use afirmação positiva, como “Ativar câmera”. A mensagem de falha não pertence ao contrato do Switch e deve ser definida pelo produto.',accessibility:'Use role=switch com aria-checked; estado deve ser perceptível sem depender apenas da cor. Disabled durante processamento impede mudanças concorrentes.',keyboard:'Tab para foco; Espaço/Enter alternam o estado pela semântica do controle. Durante State=Disabled não há alteração.',responsive:'Label pode quebrar, mas track e estado permanecem alinhados.',tokens:['size/control/md','color/bg/brand','color/bg/disabled','color/border/focus','radius/full'],edgeCases:'Persistência lenta: bloquear nova alteração sem criar variante Loading. Falha: rollback + feedback externo. Backend, timeout e copy da falha: UNKNOWN — NEEDS DEFINITION.',dependencies:'Persistência e feedback de erro são responsabilidades do consumidor; não fazem parte da API visual do Switch.',changelog:'Baseline Vellora 1.0 · responsabilidade de processing/error clarificada em 18 ago 2026.',parity:[{status:'MATCH',note:'Figma e Playground mantêm somente Checked False/True × Default/Hover/Focused/Disabled. Processing e persistence error são demonstrados como comportamento do consumidor, sem props ou variantes inventadas.'}]},

'badge':{id:'badge',name:'Badge',figma:'34:30',description:'Rótulo compacto para status, especialidade ou categoria. Use textos curtos e não dependa apenas da cor.',
figmaProps:[{name:'label',type:'string',defaultValue:'Confirmado'},{name:'size',type:'Small | Medium',defaultValue:'Small'},{name:'tone',type:'Brand | Success | Warning | Danger | Info | Neutral',defaultValue:'Brand'}],
anatomy:['Pill container','Text label'],usage:'Status, especialidade ou categoria curta.',dont:'Ação clicável, mensagem de erro completa ou único indicador de informação crítica.',
behavior:'Informativo e não recebe hover, pressed ou foco. Mudanças de status precisam ser anunciadas pelo contexto que contém o badge.',content:'1 a 2 palavras; prefira termos estáveis. Acima de cerca de 20 caracteres, reescreva.',accessibility:'Texto obrigatório; significado nunca apenas por cor.',keyboard:'Não é interativo e não entra na ordem de tabulação.',responsive:'Pode quebrar para nova linha sem reduzir tipografia.',tokens:['color/status/success/bg','color/status/success/fg','color/status/warning/bg','color/status/danger/bg','color/status/info/bg','radius/full','font/size/label'],edgeCases:'Não truncar status crítico.',dependencies:'Contexto consumidor anuncia mudança de status.',changelog:'2.0.0 · State Lab cobre Size × Tone = 12 variantes.',parity:[{status:'MATCH',note:'Small/Medium × 6 tones = 12 variantes; Brand e Success compartilham os valores cromáticos definidos no Figma.'}]},
'avatar':{id:'avatar',name:'Avatar',figma:'35:33',description:'Representa pacientes e profissionais. Iniciais são fallback; status nunca substitui rótulo textual.',
figmaProps:[{name:'initials',type:'string',defaultValue:'ML'},{name:'size',type:'Small | Medium | Large',defaultValue:'Small'},{name:'status',type:'Online | Away | Offline',defaultValue:'Online'}],
anatomy:['Circular surface','Initials','Status dot with white stroke'],usage:'Representar paciente ou profissional em contexto social.',dont:'Comprovação de identidade, diagnóstico ou dado clínico.',
behavior:'Initials é fallback atual. Status comunica disponibilidade, não presença garantida. Se imagem falhar, retorne às iniciais sem deslocar layout. V1 não expõe imagem.',content:'Iniciais do primeiro e último nome; nomes devem existir no contexto acessível.',accessibility:'Imagem decorativa quando nome já está adjacente; caso contrário forneça nome alternativo.',keyboard:'Não interativo por padrão.',responsive:'Use Size sem alterar proporção.',tokens:['size/avatar/sm','size/avatar/md','size/avatar/lg','color/bg/brand-subtle','color/text/brand','color/status/success/fg'],edgeCases:'Image prop não existe no component set v1.',dependencies:'Nome acessível vem do contexto consumidor.',changelog:'2.0.0 · State Lab cobre 9 variantes e status dot Large corrigido para a posição externa do master.',parity:[{status:'MATCH',note:'32/40/48 px, Status Online/Away/Offline e dot externo de 14 px no Large reproduzem o master 35:33.'}]},
'tabs':{id:'tabs',name:'Tabs',figma:'36:30',description:'Tab Item para alternar seções relacionadas. A composição Tabs/List materializa seleção, teclado e painel associado.',
figmaProps:[{name:'label',type:'string',defaultValue:'Resumo'},{name:'selected',type:'boolean',defaultValue:'false'},{name:'state',type:'Default | Hover | Focused | Disabled',defaultValue:'Default'}],
anatomy:['Tab item target','Label','Selected indicator: 2 px de altura e largura da caixa do label','Tabs/List example · Figma 325:2'],usage:'Alternar seções equivalentes do mesmo contexto.',dont:'Etapas sequenciais, navegação principal, filtros independentes ou conteúdo sem relação.',
behavior:'Tab Item possui 8 variantes. A composição Tabs/List controla seleção única, roving focus, ArrowLeft/ArrowRight, Home/End e painel associado. Em overflow, mantenha ativa visível e permita rolagem horizontal.',content:'Labels curtos e substantivos. Resumo/Detalhes/Documentos no Playground são EXAMPLE DATA.',accessibility:'tab, tablist e tabpanel possuem relacionamento por IDs; seleção é perceptível por forma e cor.',keyboard:'Tab entra/sai do conjunto; ArrowLeft/ArrowRight mudam seleção e foco; Home/End saltam para primeira/última aba habilitada.',responsive:'Role horizontalmente; não comprima textos até ilegíveis.',tokens:['size/control/md','color/bg/brand-subtle','color/text/brand','color/border/focus','radius/md'],edgeCases:'Recomendado 2 a 6 abas visíveis. Labels/painéis reais são dados do consumidor.',dependencies:'Composição de referência Tabs / List example · Figma 325:2; Tab Item · 36:30.',changelog:'2.0.0 · Tabs/List materializado no Figma e funcional no Playground.',parity:[{status:'MATCH',note:'Tab Item mantém 8 variantes e a composição 325:2 demonstra tablist/tabpanel sem transformar example data em contrato.'}]},

'alert':{id:'alert',name:'Alert',figma:'37:38',description:'Feedback contextual que informa estado e próximo passo. Título e mensagem devem ser específicos.',
figmaProps:[{name:'action',type:'boolean',defaultValue:'false'},{name:'actionLabel',type:'string',defaultValue:'Tentar novamente'},{name:'body',type:'string',defaultValue:'A qualidade do vídeo pode oscilar por alguns instantes.'},{name:'title',type:'string',defaultValue:'Conexão instável'},{name:'tone',type:'Info | Success | Warning | Danger',defaultValue:'Info'}],
anatomy:['Tone surface','Title','Body','Optional action'],usage:'Feedback contextual com estado, impacto e próximo passo.',dont:'Publicidade, confirmação silenciosa ou instruções longas que pertencem ao conteúdo da página.',
behavior:'Variantes: Tone Info/Success/Warning/Danger × Action False/True. Info e Warning normalmente usam anúncio não interruptivo; Danger exige prioridade apenas quando há risco imediato. Uma ação opcional deve resolver ou avançar o problema. Dismissibilidade não faz parte do contrato atual.',content:'Título específico, mensagem com causa e recuperação. Máximo de uma ação. Dismiss/close não está definido nesta família.',accessibility:'Anúncio não interruptivo é o padrão. Tone=Danger não implica role=alert; prioridade assertiva é adicionada pelo contexto somente quando houver risco imediato. Foco não é deslocado automaticamente.',keyboard:'Ação opcional: Tab para foco e Enter/Espaço para ativar. Não há controle de dismiss no contrato atual.',responsive:'Empilhe ação abaixo do texto quando faltar espaço.',tokens:['color/status/info/bg','color/status/info/fg','color/status/success/bg','color/status/warning/bg','color/status/danger/bg','radius/lg','stroke/1'],edgeCases:'Se o produto exigir dismiss/close, é necessário definir uma composição/padrão específico antes da implementação; não adicionar prop silenciosamente.',dependencies:'A ação concreta é responsabilidade do consumidor. Dismissibilidade não é dependência nem API desta família.',changelog:'Baseline Vellora 1.0 · contrato de dismissibilidade esclarecido em 18 ago 2026.',parity:[{status:'MATCH',note:'Figma e Playground expõem somente Tone × Action = 8 variantes. Não existe dismissible/close na API atual; o State Lab mostra todas as 8 variantes.'}]},

'doctor-card':{id:'doctor-card',name:'Doctor Card',figma:'38:60',description:'Apresenta profissional, especialidade, avaliação e disponibilidade.',
figmaProps:[{name:'availability',type:'Available | Busy | Offline',defaultValue:'Available'},{name:'featured',type:'boolean',defaultValue:'false'},{name:'name',type:'string',defaultValue:'Dra. Marina Lopes'},{name:'nextSlot',type:'string',defaultValue:'Hoje, 16:30'},{name:'rating',type:'string',defaultValue:'★ 4,9 · 128 avaliações'},{name:'specialty',type:'string',defaultValue:'Psicologia · CRP 06/123456'}],
anatomy:['360 × 230 card','56 px avatar placeholder','Name + specialty/registry','Rating','Availability label'],usage:'Comparação e descoberta de profissionais com disponibilidade.',dont:'Recomendação de emergência, diagnóstico automático ou ranking sem critérios transparentes.',
behavior:'Availability altera somente o texto/estilo de disponibilidade: Available usa nextSlot, Busy usa “Agenda cheia hoje”, Offline usa “Indisponível”. Featured é destaque editorial, nunca superioridade clínica. V1 não expõe ação nem loading.',content:'Nome, especialidade, registro, avaliação e próximo horário com fonte verificável.',accessibility:'Card é artigo informativo; nome/status são textuais. Não dependa de cor.',keyboard:'Não interativo por padrão. Se o produto envolver o card em um link/alvo, use um único foco e mantenha ações secundárias fora.',responsive:'Empilhe conteúdo preservando registro e disponibilidade; não invente ação interna.',tokens:['color/bg/surface','color/border/default','color/border/brand','spacing/24','spacing/16','radius/lg'],edgeCases:'Não truncar registro profissional. Skeleton/loading é composição externa.',dependencies:'Dados, interatividade e skeleton pertencem ao consumidor.',changelog:'2.0.0 · ação/loading removidos das promessas da família.',parity:[{status:'MATCH',note:'As 6 variantes Availability × Featured e suas copies padrão reproduzem o Figma.'}]},

'appointment-card':{id:'appointment-card',name:'Appointment Card',figma:'39:54',description:'Resume data, profissional e status da consulta com ação opcional apenas em combinações válidas.',
figmaProps:[{name:'action',type:'boolean',defaultValue:'false'},{name:'actionLabel',type:'string',defaultValue:'Entrar na consulta'},{name:'date',type:'string',defaultValue:'12 ago · 16:30'},{name:'professional',type:'string',defaultValue:'Dra. Marina Lopes'},{name:'status',type:'Upcoming | Today | Completed | Cancelled',defaultValue:'Upcoming'},{name:'title',type:'string',defaultValue:'Psicologia'}],
anatomy:['420 × 200 status surface','Status','Specialty title','Professional','Date','Optional action'],usage:'Resumir consulta agendada, concluída ou cancelada.',dont:'Formulário de agendamento completo ou histórico clínico detalhado.',
behavior:'6 combinações válidas no Figma: Upcoming e Today podem ter Action False/True; Completed e Cancelled existem somente com Action=False. “Entrar na consulta” depende da janela temporal do produto.',content:'Especialidade, profissional, data, hora e fuso quando relevante.',accessibility:'Leitura em ordem lógica; status textual e não dependente da cor; ação opcional é botão.',keyboard:'Ação opcional recebe foco; card em si não é controle.',responsive:'Data e ação podem empilhar sem ocultar status.',tokens:['color/status/info/bg','color/status/success/bg','color/status/danger/bg','spacing/24','spacing/12','radius/lg'],edgeCases:'Janela temporal de entrada: '+unknown+'. Completed/Cancelled nunca recebem Action=True.',dependencies:'Regra de janela para “Entrar na consulta” pertence ao produto.',changelog:'2.0.0 · variantes inválidas Completed/Cancelled + Action=True removidas do Figma (0 instâncias afetadas).',parity:[{status:'MATCH',note:'Figma e Playground agora compartilham exatamente as 6 combinações válidas.'}]},

'device-check-row':{id:'device-check-row',name:'Device Check Row',figma:'40:78',description:'Linha informativa de verificação para câmera, microfone e conexão.',
figmaProps:[{name:'detail',type:'string',defaultValue:'Verificando acesso…'},{name:'device',type:'Camera | Microphone | Connection',defaultValue:'Camera'},{name:'label',type:'string',defaultValue:'Câmera'},{name:'status',type:'Checking | Ready | Warning | Error',defaultValue:'Checking'}],
anatomy:['460 × 80 row','32 px status circle','Device label + detail','Status text'],usage:'Comunicar o resultado de verificação de câmera, microfone e conexão.',dont:'Inferir capacidade clínica, diagnosticar hardware ou colocar retry dentro da linha sem padrão definido.',
behavior:'12 variantes Device × Status. Checking evolui para Ready, Warning ou Error conforme integração. Detail é conteúdo do consumidor para causa/próximo passo; retry, timeout, permissões e troca de hardware são controles/lógica externos.',content:'Nome do dispositivo, status e detalhe textual.',accessibility:'Mudanças podem ser anunciadas; status possui texto além da cor.',keyboard:'Linha é informativa e não recebe foco. Retry externo deve ser um controle separado.',responsive:'Detail pode quebrar linha mantendo status identificável.',tokens:['color/status/info/bg','color/status/success/bg','color/status/warning/bg','color/status/danger/bg','spacing/16','radius/lg'],edgeCases:'Checking não deve ser indefinido; timeout real: '+unknown+'.',dependencies:'Permissões, teste de dispositivo, timeout e retry pertencem à integração/fluxo.',changelog:'2.0.0 · retry/timeout removidos da API implícita; State Lab cobre as 12 variantes.',parity:[{status:'MATCH',note:'A família continua informativa, sem ação inventada; Device × Status = 12 variantes.'}]},

'face-guidance-status':{id:'face-guidance-status',name:'Face Guidance Status',figma:'41:46',description:'Comunica progresso técnico de enquadramento facial. Não avalia saúde, identidade ou emoção.',
figmaProps:[{name:'detail',type:'string',defaultValue:'Olhe para a câmera'},{name:'layout',type:'Compact | Expanded',defaultValue:'Compact'},{name:'status',type:'Scanning | Ready | Warning | Error',defaultValue:'Scanning'},{name:'title',type:'string',defaultValue:'Procurando seu rosto'}],
anatomy:['Status surface','12 px signal','Title','Detail'],usage:'Orientar enquadramento, presença, distância e iluminação.',dont:'Reconhecer identidade, emoção, condição de saúde, idade, gênero ou atributo sensível.',
behavior:'O componente recebe Status; não calcula thresholds. Copies padrão do Figma mudam por status: Scanning, Ready, Warning e Error. Layout só altera dimensão.',content:'Instrução observável e próximo passo; sem linguagem diagnóstica.',accessibility:'Status textual; alternativa manual; feedback não dependente de animação; suporte a redução de movimento.',keyboard:'Informativo; não requer foco.',responsive:'Compact 360 × 72; Expanded 480 × 96; preserve texto.',tokens:['color/camera/tracking','color/camera/ready','color/camera/warning','color/camera/error','color/status/info/bg','radius/lg','stroke/2'],edgeCases:'Thresholds de estabilidade: '+unknown+'. Não armazenar biometria ou identidade.',dependencies:'Sinais técnicos/thresholds vêm da implementação validada.',changelog:'2.0.0 · copies padrão por Status sincronizadas com as variantes Figma.',parity:[{status:'MATCH',note:'8 variantes Status × Layout e suas copies padrão são reproduzidas; thresholds permanecem externos.'}]},

'camera-guidance-overlay':{id:'camera-guidance-overlay',name:'Camera Guidance Overlay',figma:'43:86',description:'Overlay para orientação técnica de enquadramento, distância, iluminação e presença. Não identifica emoções, doenças ou identidade.',
figmaProps:[{name:'controls',type:'boolean',defaultValue:'false'},{name:'detail',type:'string',defaultValue:'Mantenha os olhos na altura indicada'},{name:'status',type:'Tracking | Ready | Warning | Error',defaultValue:'Tracking'},{name:'title',type:'string',defaultValue:'Centralize seu rosto'}],
anatomy:['640 × 420 video surface','Camera overlay','220 × 290 face frame','Guide or 230 × 48 controls'],usage:'Calibração visível e consentida antes ou durante teleconsulta.',dont:'Rastreamento oculto, vigilância, identificação ou bloqueio automático sem alternativa.',
behavior:'O overlay recebe Status; não calcula thresholds. Controls=True exibe exatamente Câmera, Microfone e Sair. Retry, troca de câmera, permissão e alternativa manual pertencem ao fluxo consumidor.',content:'Copies padrão variam por Tracking/Ready/Warning/Error; explique finalidade e próximo passo.',accessibility:'Orientação textual permanece disponível para tecnologia assistiva mesmo quando Controls=True; controles são botões por teclado.',keyboard:'Controls=True: Tab, Enter/Espaço nos três controles.',responsive:'Mídia não pode expulsar controles críticos; preserve proporção e área útil.',tokens:['color/bg/video','color/camera/overlay','color/camera/tracking','color/camera/ready','color/camera/warning','color/camera/error','radius/xl'],edgeCases:'Sem retenção de frames por padrão; thresholds/processamento/retry real: '+unknown+'.',dependencies:'Consentimento, câmera, thresholds e recovery pertencem ao fluxo consumidor.',changelog:'2.0.0 · 8 variantes Status × Controls cobertas; copies padrão e controles sincronizados com o Figma.',parity:[{status:'MATCH',note:'Controls=True usa somente Câmera/Microfone/Sair; copies variam por Status como no Figma.'}]},

'call-control':{id:'call-control',name:'Call Control',figma:'205:62',description:'Controle rotulado para ações essenciais da teleconsulta. Mantém alvo de toque de 52 px e significado que não depende apenas de cor.',
figmaProps:[{name:'icon',type:'INSTANCE_SWAP / ReactNode',defaultValue:'Icon/Mic'},{name:'label',type:'string',defaultValue:'Microfone'},{name:'state',type:'Default | Active | Focused | Disabled',defaultValue:'Default'},{name:'tone',type:'Neutral | Danger | Inverse',defaultValue:'Neutral'}],
anatomy:['68 × 80 wrapper','52 × 52 circular target','24 × 24 semantic icon','Visible 12 px label'],usage:'Microfone, câmera, chat, dispositivos e encerramento durante vídeo.',dont:'Tone Danger fora de encerrar/sair; Tone Inverse fora de vídeo/superfície escura.',
behavior:'Active é estado persistente do controle alternável e muda tratamento visual. Figma possui apenas um Label e um Icon por instância; se o significado da ação mudar quando alternada, o consumidor atualiza esses mesmos props junto com State. Não existem activeLabel/activeIcon.',content:'Rótulo visível e accessible name equivalentes. Use rótulo semântico para a ação atual no contexto consumidor.',accessibility:'Alvo 52 × 52; controles não-Danger expõem aria-pressed conforme State=Active; significado não depende só de cor.',keyboard:'Tab para foco; Enter/Espaço ativa. Danger dispara ação única; Neutral/Inverse podem alternar Active.',responsive:'Não reduzir alvo ou rótulo em compact.',tokens:['size/control/lg','size/icon/lg','color/border/focus','color/border/video','color/status/danger/bg','radius/full'],edgeCases:'Mudança semântica de label/icon deve ser atômica com State, usando as propriedades existentes.',dependencies:'Icon library; confirmação de encerramento para Tone=Danger pertence ao fluxo.',changelog:'2.0.0 · activeLabel/activeIcon inventados removidos do Playground; API agora espelha o Figma.',parity:[{status:'MATCH',note:'Tone × State = 12 variantes; Label/Icon únicos por instância, sem props paralelas.'}]},

'desktop-header':{id:'desktop-header',name:'Desktop Header',figma:'236:70',description:'Navegação principal do paciente em desktop. Mantém marca, rotas globais, notificações e avatar.',
figmaProps:[{name:'active',type:'Início | Especialistas | Agenda | Documentos',defaultValue:'Início'}],
anatomy:['1440 × 80 header','1200 px central content via 120 px side padding','32 px Vellora mark','Primary navigation pills','44 px notification Icon Button','40 px Avatar · Medium · Online','12 px gap entre ações'],usage:'Telas desktop do paciente em viewport ≥768 px.',dont:'Viewport abaixo de 768 px.',
behavior:'Uma rota ativa. Ativa usa brand-subtle + text brand. Notificação e Avatar permanecem à direita. Quatro variantes Active correspondem às rotas publicadas.',content:'Rotas: Início, Especialistas, Agenda, Documentos.',accessibility:'nav possui nome; rota ativa usa aria-current; foco visível funcional; Avatar expõe status textual sem substituir iniciais.',keyboard:'Tab entre rotas e notificações; Enter/Espaço ativa.',responsive:'Mostrar somente ≥768 px. Abaixo de 768 px, o produto usa Bottom navigation existente nos fluxos mobile; ele não é uma família publicada do Desktop Header v1.',tokens:['color/bg/surface','color/bg/brand-subtle','color/text/brand','color/border/focus','size/control/md'],edgeCases:'Identidade do paciente é dinâmica no produto, mas não é prop do component set; a composição mantém Avatar Medium/Online como referência visual.',dependencies:'Icon Button + Icon/Bell + Avatar. Bottom navigation é padrão do produto fora desta família.',changelog:'2.0.0 · breakpoint corrigido para <768 px e status da navegação mobile explicitado.',parity:[{status:'MATCH',note:'4 variantes Active, avatar visível, gap 12 px e breakpoint ≥768 px sincronizados.'}]}

}

export const iconNames=['Home','Search','Calendar','Clock','User','Users','Bell','Settings','Menu','More Vertical','Chevron Left','Chevron Right','Chevron Down','Arrow Left','Close','Check','Info','Warning','Error','Video','Video Off','Mic','Mic Off','Phone','Chat','Send','Camera','Camera Off','Stethoscope','Heart Pulse','Brain Care','Nutrition','Medical Record','Face Scan','Frame Center','Rotate Camera','Light','Shield Check','Lock'] as const

export const tokenValues:Record<string,string>={
'color/action/primary/default':'#0E745B','color/action/primary/hover':'#0A5C49','color/action/primary/pressed':'#08483B',
'color/action/destructive/default':'#B42318','color/action/destructive/hover':'#912018','color/action/destructive/pressed':'#912018',
'color/border/default':'#D7E1DD','color/border/strong':'#879992','color/border/focus':'#008C95','color/border/danger':'#D92D20','color/border/brand':'#0E745B','color/border/video':'#1F2937',
'color/bg/surface':'#FFFFFF','color/bg/brand':'#0E745B','color/bg/brand-subtle':'#E5F3EE','color/bg/disabled':'#E9EFEC','color/bg/video':'#0B1210',
'color/text/brand':'#0A5C49','color/status/success/bg':'#E5F3EE','color/status/success/fg':'#0A5C49','color/status/warning/bg':'#FFFAEB','color/status/warning/fg':'#B54708','color/status/danger/bg':'#FEF3F2','color/status/danger/fg':'#B42318','color/status/info/bg':'#EFF8FF','color/status/info/fg':'#175CD3',
'color/camera/tracking':'#94D2BC','color/camera/ready':'#5FB79A','color/camera/warning':'#F79009','color/camera/error':'#D92D20','color/camera/overlay':'rgba(11,18,16,.4)',
'size/control/md':'44px','size/control/lg':'52px','size/icon/md':'20px','size/icon/lg':'24px','size/avatar/sm':'32px','size/avatar/md':'40px','size/avatar/lg':'48px',
'radius/sm':'4px','radius/md':'8px','radius/lg':'12px','radius/xl':'16px','radius/full':'9999px','spacing/24':'24px','spacing/16':'16px','spacing/12':'12px','stroke/1':'1px','stroke/2':'2px','font/size/body-medium':'16px','font/size/label':'14px'
}
